export const banksArr = [
  " Click to Select",
  "Access Bank Plc",
  "Fidelity Bank Plc",
  "First City Monument Bank Limited",
  "First Bank of Nigeria Limited",
  "Guaranty Trust Holding Company Plc",
  "Union Bank of Nigeria Plc",
  "United Bank for Africa Plc",
  "Zenith Bank Plc",
  "Citibank Nigeria Limited",
  "Ecobank Nigeria",
  "Heritage Bank Plc",
  "Keystone Bank Limited",
  "Polaris Bank Limited",
  "Stanbic IBTC Bank Plc",
  "Standard Chartered",
  "Sterling Bank Plc",
  "Titan Trust Bank Limited",
  "Unity Bank Plc",
  "Wema Bank Plc",
  "Kuda Bank",
  "Opay",
  "Palmpay",
  "VFD Microfinance Bank",
];
banksArr.sort();
